FROM python:3.9-slim-buster

# Install curl, bash, and PostgreSQL development libraries
RUN apt-get update && apt-get install -y \
    curl \
    bash \
    libpq-dev \
    gcc \
    && apt-get clean

# Set working directory inside the container
WORKDIR /app

# Copy only the app.py file into the container
COPY app.py /app/app.py

# Copy requirements.txt into the container
COPY requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 80 to be able to access it
EXPOSE 80

# Set environment variable to tell Flask to listen on all interfaces
ENV FLASK_RUN_HOST=0.0.0.0

# Command to run the Flask app
CMD ["python", "app.py"]